#!/bin/sh

##
# HubSpot API engagements download
#
# Syntax:
#
#     hubspot-api-engagements-download
#
# This tool is for [HubSpot](https://hubspot.com) account users.
# This tool connects to the HubSpot API and downloads engagements.
#
# The output is a series of JSON files with file names that
# show the offset number and the requested record count limit.
#
# Example output file names:
#
#     engagements-offset-0-limit-300.json
#     engagements-offset-300-limit-300.json
#     engagements-offset-600-limit-300.json
#
# This tool also combines the files' engagements into one file name:
#
#     engagements.json
#
# Author: joel@joeparkerhenderson.com
##

##
#
# sixarm-unix-shell-functions library
#
##

# out: print output message to stdout
out() { printf %s\\n "$*" ; }

# err: print error message to stderr
err() { >&2 printf %s\\n "$*" ; }

# die: print error message to stderr, then exit with error code 1
die() { >&2 printf %s\\n "$*" ; exit 1 ; }

# cmd: return true iff a command exists
cmd() { command -v "$1" >/dev/null 2>&1 ; }

##
#
# HubSpot API
#
##

# Get HubSpot API URI to download
# Syntax: uri $offset $limit
uri() {
    echo "https://api.hubapi.com/engagements/v1/engagements/paged?hapikey=$HUBSPOT_API_KEY&offset=$offset&limit=$limit"
}

# Get name to save the data file
# Syntax: file_name $offset $limit
file_name() {
    echo "engagements-offset-$offset-limit-$limit.json"
}

# Does the file indicate that there's more to download?
# Syntax: file_has_more $file_name
file_has_more() {
    jq '."hasMore"' "$1"
}

# Get the file's HubSpot offset for the next request
# Syntax: file_vid_offset $file_name
file_offset() {
    jq '."offset"' "$1"
}

# Get the number of JSON engagement items in a file
# Syntax: file_objects_length $file_name
file_objects_length() {
    jq '.results | length' "$1"
}

# Combine all the response contacts files into one big file
# Syntax: file_join
file_join() {
    jq -s 'reduce .[].results as $item ([]; . + $item)' engagements-offset-*-limit-*.json > engagements.json
}

# Verify preflight
# Syntax: preflight
preflight() {
    [ -z ${HUBSPOT_API_KEY+x} ] && die "Environment needed: HUBSPOT_API_KEY"
    cmd curl || die "Command needed: curl (HTTP downloader)"
    cmd jq || die "Command needed: jq (JSON processor)"
}

# Main function
# Syntax: main
main() {
    offset=1224171342
    limit=250
    while true; do
        file_name=$(file_name $offset $limit)
        echo "file:$file_name"
        test -e "$file_name" || curl -s $(uri $offset $limit) > "$file_name"
        more=$(file_has_more "$file_name")
        if [ "$more" != "true" ]; then
            break
        fi
        offset=$(file_offset "$file_name")
    done
    file_join
}

preflight
main
exit 0
