#!/bin/sh

##
# HubSpot API engagements download
#
# Syntax:
#
#     hubspot-api-engagements-download
#
# This tool is for [HubSpot](https://hubspot.com) account users.
# This tool connects to the HubSpot API and downloads engagements.
#
# The output is a series of JSON files with file names that
# show the offset number and the requested record count limit.
#
# Example output file names:
#
#     engagements-offset-0-limit-250.json
#     engagements-offset-250-limit-250.json
#     engagements-offset-500-limit-250.json
#
# This tool also combines the files' engagements into one file name:
#
#     engagements.json
#
# Author: joel@joelparkerhenderson.com
##

set -euf

# Include https://github.com/SixArm/posix-shell-script-kit
. "$(dirname "$(readlink -f "$0")")/posix-shell-script-kit"

##
#
# HubSpot API
#
##

# Get HubSpot API URI to download
# Syntax: uri $offset $limit
uri() {
    echo "https://api.hubapi.com/engagements/v1/engagements/paged?hapikey=$HUBSPOT_API_KEY&offset=$offset&limit=$limit"
}

# Get name to save the data file
# Syntax: file_name $offset $limit
file_name() {
    echo "engagements-offset-$offset-limit-$limit.json"
}

# Does the file indicate that there's more to download?
# Syntax: file_has_more $file_name
file_has_more() {
    jq '."hasMore"' "$1"
}

# Get the file's HubSpot offset for the next request
# Syntax: file_vid_offset $file_name
file_offset() {
    jq '."offset"' "$1"
}

# Get the number of JSON engagement items in a file
# Syntax: file_objects_length $file_name
file_objects_length() {
    jq '.results | length' "$1"
}

# Combine all the response contacts files into one big file
# Syntax: file_join
file_join() {
    jq -s 'reduce .[].results as $item ([]; . + $item)' engagements-offset-*-limit-*.json > engagements.json
}

# Verify preflight
# Syntax: preflight
preflight() {
    [ -z ${HUBSPOT_API_KEY+x} ] && die "Environment needed: HUBSPOT_API_KEY"
    command_exists_or_die curl
    command_exists_or_die jq
}

# Main function
# Syntax: main
main() {
    offset=1224171342
    limit=250
    while true; do
        file_name=$(file_name $offset $limit)
        echo "file:$file_name"
        test -e "$file_name" || curl -s $(uri $offset $limit) > "$file_name"
        more=$(file_has_more "$file_name")
        if [ "$more" != "true" ]; then
            break
        fi
        offset=$(file_offset "$file_name")
    done
    file_join
}

preflight
main
exit 0
